// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void google() {
    // Test name: Google
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.google.com/");
    // 2 | setWindowSize | 1440x789 | 
    driver.manage().window().setSize(new Dimension(1440, 789));
    // 3 | type | name=q | selenium
    driver.findElement(By.name("q")).sendKeys("selenium");
    // 4 | click | css=.sbhl .wM6W7d > span | 
    driver.findElement(By.cssSelector(".sbhl .wM6W7d > span")).click();
    // 5 | mouseOver | css=div:nth-child(3) > .tF2Cxc .LC20lb | 
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .tF2Cxc .LC20lb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | click | css=div:nth-child(3) > .tF2Cxc .LC20lb | 
    driver.findElement(By.cssSelector("div:nth-child(3) > .tF2Cxc .LC20lb")).click();
    // 7 | mouseOut | css=div:nth-child(3) > .tF2Cxc .LC20lb | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | click | css=.selenium-ide:nth-child(2) | 
    driver.findElement(By.cssSelector(".selenium-ide:nth-child(2)")).click();
    // 9 | click | css=.selenium-ide:nth-child(2) | 
    driver.findElement(By.cssSelector(".selenium-ide:nth-child(2)")).click();
    // 10 | doubleClick | css=.selenium-ide:nth-child(2) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".selenium-ide:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 11 | click | css=.selenium-ide:nth-child(2) | 
    driver.findElement(By.cssSelector(".selenium-ide:nth-child(2)")).click();
    // 12 | assertText | css=.selenium-ide:nth-child(2) | Selenium IDE
    assertThat(driver.findElement(By.cssSelector(".selenium-ide:nth-child(2)")).getText(), is("Selenium IDE"));
  }
}
